name: fmt

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'feature/'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      # fmt 確認 
      - name: fmt checks
        run: |
          go vet
      # fmt 確認 
      - name: fmt2 checks
        run: |
          go fmt