name: fmt

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      # fmt 確認 
      - name: fmt checks
        run: |
          go vet
      # fmt 確認 
      - name: fmt2 checks
        run: |
          go fmt
        # buildテスト
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: go build ./...